In [1]:
import pandas as pd

In [4]:
data1 = {u'/Airtel-03/TemperatureSensor100/Errors': 23.0,
 u'/Airtel-03/TemperatureSensor100/LastUpdate': 48.0,
 u'/Airtel-03/TemperatureSensor100/RSSI': 573.0,
 u'/Airtel-03/TemperatureSensor100/ReadErrors': 0,
 u'/Airtel-03/TemperatureSensor100/Reboots': 48.0,
 u'/Airtel-03/TemperatureSensor100/ReconnectReboots': 48.0,
 u'/Airtel-03/TemperatureSensor100/Reconnects': 48.0,
 u'/Airtel-03/TemperatureSensor100/Temperature': 2878.0,
 u'/Airtel-03/TemperatureSensor100/TemperatureReboots': 48.0,
 u'/Airtel-03/TemperatureSensor100/ValuesReceived': 2876.0}

In [8]:
data2 = {u'/Airtel-03/TemperatureSensor100/Errors': 23.0,
 u'/Airtel-03/TemperatureSensor100/LastUpdate': 48.0,
 u'/Airtel-03/TemperatureSensor100/RSSI': 573.0,
 u'/Airtel-03/TemperatureSensor100/ReadErrors': 0,
 u'/Airtel-03/TemperatureSensor100/Reboots': 48.0,
 u'/Airtel-03/TemperatureSensor100/ReconnectReboots': 48.0,
 u'/Airtel-03/TemperatureSensor100/Reconnects': 48.0,
 u'/Airtel-03/TemperatureSensor100/Temperature': 2878.0,
 u'/Airtel-03/TemperatureSensor100/TemperatureReboots': 48.0,
 u'/Airtel-03/TemperatureSensor100/ValuesReceived': 0.0}

In [10]:
# create a dataframe with two columns and one index column from two dictionaries
df = pd.DataFrame.from_dict(data={'one':data1, 'two': data2})
df

                                                       one     two
/Airtel-03/TemperatureSensor100/Errors                23.0    23.0
/Airtel-03/TemperatureSensor100/LastUpdate            48.0    48.0
/Airtel-03/TemperatureSensor100/RSSI                 573.0   573.0
/Airtel-03/TemperatureSensor100/ReadErrors             0.0     0.0
/Airtel-03/TemperatureSensor100/Reboots               48.0    48.0
/Airtel-03/TemperatureSensor100/ReconnectReboots      48.0    48.0
/Airtel-03/TemperatureSensor100/Reconnects            48.0    48.0
/Airtel-03/TemperatureSensor100/Temperature         2878.0  2878.0
/Airtel-03/TemperatureSensor100/TemperatureReboots    48.0    48.0
/Airtel-03/TemperatureSensor100/ValuesReceived      2876.0     0.0

In [11]:
# create a new column with the difference of the first two columns
df.assign(three=df.one - df.two)

                                                       one     two   three
/Airtel-03/TemperatureSensor100/Errors                23.0    23.0     0.0
/Airtel-03/TemperatureSensor100/LastUpdate            48.0    48.0     0.0
/Airtel-03/TemperatureSensor100/RSSI                 573.0   573.0     0.0
/Airtel-03/TemperatureSensor100/ReadErrors             0.0     0.0     0.0
/Airtel-03/TemperatureSensor100/Reboots               48.0    48.0     0.0
/Airtel-03/TemperatureSensor100/ReconnectReboots      48.0    48.0     0.0
/Airtel-03/TemperatureSensor100/Reconnects            48.0    48.0     0.0
/Airtel-03/TemperatureSensor100/Temperature         2878.0  2878.0     0.0
/Airtel-03/TemperatureSensor100/TemperatureReboots    48.0    48.0     0.0
/Airtel-03/TemperatureSensor100/ValuesReceived      2876.0     0.0  2876.0